=pod

=head1 NAME

knradio - interface for knradio, 92,2 FM

=head1 DESCRIPTION

knradio is a command line interface for the "knradio" radio station.

=head1 OPTIONS

  -np, --now-playing     print the currently playing song title
  -p,  --play            start playback
  -s,  --stop            stop playback
  -l,  --log             log playlist history to file
  -f,  --fav             add now playing song to favorites
  -lf, --list            list favorites
  -n,  --no-daemon       don't fork into the background

  -h,   --help           show this help
  -v,   --version        show version info

=head1 AUTHOR

  Magnus japh Woldrich
  CPAN ID: WOLDRICH
  m@japh.se
  http://japh.se

=head1 CONTRIBUTORS

Floff, for finding the np-url in the javascript mess.

=head1 REPORTING BUGS

Report bugs and/or feature requests to <m@japh.se>.

=head1 COPYRIGHT

Copyright 2016 the B<knradio> L</AUTHOR> as listed above.

=head1 LICENSE

This application is free software; you may redistribute it and/or modify it
under the same terms as Perl itself.

=head1 SEE ALSO

L<http://knradio.se>

=cut
